<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CS-075-LT-WS" name="Test" tests="3" failures="1" timestamp="17 May 2018 07:30:53 GMT" time="11.15" errors="0">
  <testcase name="@AfterTest end" time="0.0" classname="com.circlesLife.TestCases.FacebookAutomationTestCase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.circlesLife.TestCases.FacebookAutomationTestCase.end(FacebookAutomationTestCase.java:57)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest end -->
  <testcase name="verifyWebsiteLaunch" time="10.942" classname="com.circlesLife.TestCases.CirclesLifeAutomationTestCases"/>
  <testcase name="loginToCirclesLifeWebsite" time="0.009" classname="com.circlesLife.TestCases.CirclesLifeAutomationTestCases"/>
  <testcase name="verifyAppiumConnectionAndAppLuanch" time="0.016" classname="com.circlesLife.TestCases.FacebookAutomationTestCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.circlesLife.TestCases.FacebookAutomationTestCase.verifyAppiumConnectionAndAppLuanch(FacebookAutomationTestCase.java:40)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyAppiumConnectionAndAppLuanch -->
</testsuite> <!-- Test -->
